package cs1302.arcade;

import java.util.Random;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
import javafx.event.EventHandler;
import javafx.scene.input.KeyEvent;
import javafx.scene.input.KeyCode;
import javafx.scene.input.MouseEvent;
import javafx.scene.image.ImageView;
import javafx.scene.image.Image;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.layout.StackPane;
import javafx.geometry.Pos;

public class ArcadeApp extends Application {

    Group group = new Group();           // main container

    /**
     * Return a mouse event handler that moves to the rectangle to a random
     * position any time a mouse event is generated by the associated node.
     * @return the mouse event handler
     */
    private EventHandler<? super MouseEvent> createMouseHandler() {
        return event -> {
            if(event.getY() < 385) {
                System.out.println("Launch 2048!");
            } else if(event.getY() >= 385) {
                System.out.println("Launch Space Invaders!");
            }
        };
    } // createMouseHandler
    
    
    /** {@inheritdoc} */
    @Override
    public void start(Stage stage) {
        StackPane sp2048 = new StackPane();
        StackPane spInvaders = new StackPane();
        VBox vbox = new VBox();

        //Creating 2048 box
        ImageView start = new ImageView(new Image("file:images/2048/2048StartButton.png"));
        sp2048.getChildren().add(new ImageView(new Image("file:images/2048/2048Background.png")));
        sp2048.getChildren().add(start);
        sp2048.setAlignment(start,Pos.BOTTOM_CENTER); 
        

        //Creating Space Invaders box
        spInvaders.getChildren().add(new ImageView(new Image("file:images/spaceInv/siBackground.jpg")));

        group.setOnMouseClicked(createMouseHandler());
        vbox.getChildren().addAll(sp2048, spInvaders);
        group.getChildren().add(vbox);
        
        Scene scene = new Scene(group, 1024, 768);
        stage.setTitle("cs1302-arcade!");
        stage.setScene(scene);
        stage.sizeToScene();
        stage.setFullScreen(true);
        stage.show();

        // the group must request input focus to receive key events
        // @see https://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html#requestFocus--
        group.requestFocus();

    } // start

} // ArcadeApp
